# Generated by Django 4.2 on 2023-05-10 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wikis", "0002_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="wiki",
            name="name",
            field=models.TextField(default="temp_name"),
            preserve_default=False,
        ),
    ]
