# Generated by Django 4.2 on 2023-05-10 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wikis", "0004_remove_wiki_name_wiki_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(default="temp-slug"),
            preserve_default=False,
        ),
    ]
