# Generated by Django 4.2 on 2023-05-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wikis", "0005_post_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="MathBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("image_link", models.TextField()),
                ("file_link", models.TextField()),
            ],
        ),
    ]
