# Generated by Django 4.2 on 2023-05-11 14:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("wikis", "0006_mathbook"),
    ]

    operations = [
        migrations.AddField(
            model_name="mathbook",
            name="year_used",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
