# Generated by Django 4.2 on 2023-07-12 20:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("wikis", "0008_mathbook_author_alter_mathbook_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecretPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("image_link", models.TextField()),
                ("description", models.TextField()),
            ],
        ),
    ]
